# Generated by Django 5.1.3 on 2024-11-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=255)),
                ('material_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('inventory', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.supplier')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.materialcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=255)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_line_code', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('marterial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.material')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.order')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=255)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.order')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_line_code', models.CharField(max_length=255, null=True)),
                ('quantity_order', models.IntegerField(blank=True, null=True)),
                ('quantity_receipt', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.material')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.receipt')),
            ],
        ),
    ]
