# Generated by Django 5.1.3 on 2024-11-21 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_materialcategory_material_order_orderline_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_code', models.CharField(max_length=255)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=255)),
                ('room_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=10000, null=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_line_code', models.CharField(max_length=255, null=True)),
                ('quantity_delivered', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.delivery')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.material')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='production_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.productionroom'),
        ),
    ]
