# Generated by Django 5.1.3 on 2025-01-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delivery_productionroom_deliveryline_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialCategory',
            new_name='Category',
        ),
    ]
