# Generated by Django 5.1.3 on 2025-01-23 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_materialcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryline',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryline',
            name='material',
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=255)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('production_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.productionroom')),
            ],
        ),
        migrations.CreateModel(
            name='IssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_line_code', models.CharField(max_length=255, null=True)),
                ('quantity_delivered', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.issue')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.material')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryLine',
        ),
    ]
