# Generated by Django 5.1.3 on 2025-01-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_deliveryline_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='delivery_date',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='order_date',
        ),
    ]
