# Generated by Django 5.1.3 on 2025-02-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_order_material_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
