# Generated by Django 5.1.3 on 2025-02-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_order_material_remove_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='marterial',
            new_name='material',
        ),
    ]
