# Generated by Django 5.1.3 on 2025-02-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
