# Generated by Django 5.1.3 on 2025-02-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_message_rename_tax_code_supplier_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='material',
            name='notes',
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='material',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
