# Generated by Django 5.1.3 on 2025-02-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_material_category_remove_material_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unit_of_measure',
        ),
    ]
