# Generated by Django 5.1.3 on 2025-02-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_material_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='zalo',
        ),
    ]
