# Generated by Django 5.1.3 on 2025-02-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_material_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
