# Generated by Django 5.1.3 on 2025-02-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_issue_issue_date_alter_message_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_amount',
        ),
    ]
