# Generated by Django 5.1.3 on 2025-02-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_rename_total_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='related_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='receiptline',
            old_name='quantity_order',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='receiptline',
            old_name='total_price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='receiptline',
            name='quantity_receipt',
        ),
        migrations.AddField(
            model_name='receipt',
            name='count_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shipping_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='vat_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='IssueLine',
        ),
    ]
