# Generated by Django 5.1.3 on 2025-02-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_rename_related_order_receipt_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_date',
        ),
    ]
