# Generated by Django 5.1.3 on 2025-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_remove_receipt_receipt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='count_per_day',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
