# Generated by Django 5.1.3 on 2025-02-20 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_collection_employee_productcategory_producttype_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=10)),
                ('ordering_color', models.CharField(max_length=10)),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_code', models.CharField(max_length=10)),
                ('design_name', models.CharField(max_length=255)),
                ('is_set', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='design_images/')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.collection')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.employee')),
                ('lining_fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lining_fabric_designs', to='catalog.material')),
                ('main_fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='main_fabric_designs', to='catalog.material')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.productcategory')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ColorInDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.color')),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.design')),
            ],
        ),
        migrations.CreateModel(
            name='SizeInDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.design')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.size')),
            ],
        ),
    ]
