# Generated by Django 5.1.3 on 2025-02-20 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_color_design_colorindesign_sizeindesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU_code', models.CharField(max_length=10)),
                ('SKU_name', models.CharField(max_length=255)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.color')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.design')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.size')),
            ],
        ),
    ]
