# Generated by Django 5.1.3 on 2025-02-21 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='SKU_code',
            new_name='sku_code',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='SKU_name',
            new_name='sku_name',
        ),
        migrations.AlterField(
            model_name='design',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.collection'),
        ),
        migrations.AlterField(
            model_name='design',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.employee'),
        ),
        migrations.AlterField(
            model_name='design',
            name='is_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='lining_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lining_fabric_designs', to='catalog.material'),
        ),
        migrations.AlterField(
            model_name='design',
            name='main_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='main_fabric_designs', to='catalog.material'),
        ),
        migrations.AlterField(
            model_name='design',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.productcategory'),
        ),
        migrations.AlterField(
            model_name='design',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.producttype'),
        ),
    ]
