# Generated by Django 5.1.3 on 2025-02-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_rename_sku_code_sku_sku_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorindesign',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.color'),
        ),
    ]
