# Generated by Django 5.1.3 on 2025-02-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_colorindesign_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='lining_fabric',
        ),
        migrations.RemoveField(
            model_name='design',
            name='main_fabric',
        ),
        migrations.AlterField(
            model_name='colorindesign',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.color'),
        ),
    ]
