# Generated by Django 5.1.3 on 2025-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_remove_design_lining_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sku_images/'),
        ),
    ]
