# Generated by Django 5.1.3 on 2025-02-26 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_collection_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.sku')),
            ],
        ),
    ]
