# Generated by Django 5.1.3 on 2025-02-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_inventorysku'),
    ]

    operations = [
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_code', models.CharField(max_length=10)),
                ('qc_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.employee')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.sku')),
            ],
        ),
    ]
