# Generated by Django 5.1.3 on 2025-02-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='order_status',
            field=models.CharField(choices=[('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='completed', max_length=10),
        ),
    ]
