# Generated by Django 5.1.3 on 2025-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_qc_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='order_status',
            field=models.CharField(choices=[('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='completed', max_length=10),
        ),
    ]
