# Generated by Django 5.1.3 on 2025-02-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_qc_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_code', models.CharField(max_length=10)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='completed', max_length=10)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_line_code', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('import_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.import')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.sku')),
            ],
        ),
    ]
