# Generated by Django 5.1.3 on 2025-02-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_export_exportline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='completed', max_length=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='completed', max_length=10),
        ),
    ]
