# Generated by Django 5.1.3 on 2025-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_material_stock_max_material_stock_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
