# Generated by Django 5.1.3 on 2025-03-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Đang làm việc'), ('inactive', 'Đã nghỉ việc')], default='Active', max_length=10),
        ),
    ]
