# Generated by Django 5.1.3 on 2025-03-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_alter_employee_employment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='notes',
        ),
    ]
