# Generated by Django 5.1.3 on 2025-03-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_remove_employee_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_code', models.CharField(max_length=50, unique=True)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('design_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.design')),
                ('tailor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=50, unique=True)),
                ('task_name', models.CharField(blank=True, max_length=10, null=True)),
                ('main_fabric_meters', models.FloatField()),
                ('lining_fabric_meters', models.FloatField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('In Progress', 'Dở dang'), ('Completed', 'Hoàn thành')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.progress')),
            ],
        ),
    ]
