# Generated by Django 5.1.3 on 2025-03-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_progress_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='lining_fabric_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='main_fabric_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'Dở dang'), ('Completed', 'Hoàn thành')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='task_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
