# Generated by Django 5.1.3 on 2025-03-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_progress_end_time_progress_lining_fabric_meters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('sku_name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('sewing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('main_fabric_meters', models.FloatField(blank=True, null=True)),
                ('lining_fabric_meters', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='completed', max_length=10)),
                ('design_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.design')),
                ('lining_fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lining_fabric_set', to='catalog.material')),
                ('main_fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='main_fabric_set', to='catalog.material')),
                ('sku_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.sku')),
                ('tailor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.employee')),
            ],
        ),
    ]
