# Generated by Django 5.1.3 on 2025-03-06 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='sku_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='sku_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.sku'),
        ),
    ]
