# Generated by Django 5.1.3 on 2025-03-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_alter_issue_sku_code_alter_issue_sku_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='design_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
